CREATE TABLE STAT (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_LILITH VARCHAR(30) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    POWER VARCHAR(40) NOT NULL,
    T4_KILLS VARCHAR(20) NOT NULL,
    T5_KILLS VARCHAR(20) NOT NULL,
    TOTAL_KILLS VARCHAR(30) NOT NULL,
    DEATH VARCHAR(30) NOT NULL,
    DATE_UPDATE DATE NOT NULL
);

